name: conda-env-01
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.9=py313hd8ed1ab_100
  - debugpy=1.8.17=py313h5d5ffb9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - icu=73.1=h6a678d5_0
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_6
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=38_h47877c9_openblas
  - libmpdec=4.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h28b3bda_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - lxml=5.3.0=py313h57af460_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.4=py313hf6604e3_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h07c4f96_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.7=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_100
  - python_abi=3.13=1_cp313
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.3=hc2a1206_0
  - scikit-learn=1.7.2=py313h06d4379_0
  - setuptools=80.9.0=py313h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py313h07c4f96_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - uv=0.9.4=h30787bc_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - beautifulsoup4==4.14.2
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.60.1
      - gensim==4.4.0
      - kiwisolver==1.4.9
      - kneed==0.8.5
      - matplotlib==3.10.7
      - nltk==3.9.2
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.2.5
      - pytz==2025.2
      - regex==2025.10.23
      - scipy==1.16.2
      - seaborn==0.13.2
      - smart-open==7.4.1
      - soupsieve==2.8
      - tqdm==4.67.1
      - tzdata==2025.2
      - wrapt==2.0.0
prefix: /home/iceyisaak/anaconda3/envs/conda-env-01
